---

- name: Ensure Composer PPA exists in repository
  apt_repository:
    repo: "{{ composer_ppa }}"

- name: Ensure Composer is installed
  apt:
    name: php5-composer
    state: present
    update_cache: yes
    cache_valid_time: 3600